---
- name: Check Nano installation on EKS nodes via SSM
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:
    - name: Run SSM command to check for nano
      amazon.aws.ssm:
        region: us-east-1
        targets:
          - Key: tag:Name
            Values: ["my_node"]   # adjust this tag to match your EC2 nodes
        document_name: AWS-RunShellScript
        parameters:
          commands:
            - "which nano || echo 'nano not installed'"
      register: ssm_output

    - name: Display SSM output
      debug:
        var: ssm_output
