- name: Test SSM module
  hosts: all
  gather_facts: false
  connection: amazon.aws.aws_ssm
  tasks:
    - name: Run simple command via SSM
      amazon.aws.aws_ssm_command:
        targets:
          - "{{ inventory_hostname }}"
        document_name: "AWS-RunShellScript"
        parameters:
          commands:
            - "echo hello"
      register: test
    - debug:
        var: test
