- name: Check if nano is installed
  hosts: all
  connection: amazon.aws.aws_ssm
  gather_facts: false
  tasks:
    - name: Run which nano
      command: which nano
      register: nano_check
      ignore_errors: yes

    - name: Report nano status
      debug:
        msg: >
          Nano is {{
            'installed' if (nano_check.stdout_lines | default([]) | join('') | trim != '') else 'not installed'
          }} on {{ inventory_hostname }}
