---
- name: Check if nano has been installed
  hosts: all
  gather_facts: no
  become: yes
  vars:
    ansible_connection: amazon.aws.aws_ssm
    ansible_user: ec2-user
    
  tasks:
    - name: Ensure nano is installed
      ansible.builtin.yum:
        name: nano
        state: present
