---
- name: Check if nano has been installed
  hosts: all
  gather_facts: no
  become: yes

  tasks:
    - name: Ensure nano is installed
      ansible.builtin.yum:
        name: nano
        state: present
