---
- name: Check if nano has been installed
  hosts: all
  gather_facts: no
  become: yes

  tasks:
    - name: Ensure nano is installed via SSM
      amazon.aws.ssm_command:
        document_name: AWS-RunShellScript
        targets:
          - Key: InstanceIds
            Values:
              - "{{ inventory_hostname }}"
        parameters:
          commands:
            - sudo yum install -y nano
