---
- name: Check if nano has been installed
  hosts: all
  connection: amazon.aws.aws_ssm
  become: yes
  gather_facts: false

  tasks:
    - name: Ensure nano is installed
      yum:
        name: nano
        state: present
