- name: Check if nano is installed on EKS nodes
  hosts: all
  connection: amazon.aws.aws_ssm
  gather_facts: false
  tasks:
    - name: Report nano status
      debug:
        msg: >
          Nano is {{
            'installed' if (nano_check.stdout | trim != '') else 'not installed'
          }} on {{ inventory_hostname }}
