---
- name: Check if nano has been installed
  hosts: all
  gather_facts: no
  become: yes
  collections:
    - amazon.aws

  tasks:
    - name: Ensure nano is installed via SSM
      aws_ssm:
        document_name: AWS-RunShellScript
        targets:
          - Key: InstanceIds
            Values:
              - "{{ inventory_hostname }}"
        parameters:
          commands:
            - sudo yum install -y nano
