---
- name: Install nano on EKS nodes via SSM
  hosts: all
  gather_facts: no
  become: yes
  collections:
    - amazon.aws

  tasks:
    - name: Ensure nano is installed via SSM
      amazon.aws.aws_ssm:
        targets:
          - Key: InstanceIds
            Values:
              - "{{ inventory_hostname }}"
        document_name: AWS-RunShellScript
        parameters:
          commands:
            - sudo yum install -y nano
