- name: Check if nano is installed on EKS nodes
  hosts: all
  connection: amazon.aws.aws_ssm
  gather_facts: false
  tasks:
    - name: Check if nano exists
      amazon.aws.aws_ssm_command:
        targets:
          - "{{ inventory_hostname }}"
        document_name: "AWS-RunShellScript"
        parameters:
          commands:
            - "which nano || echo ''"
      register: nano_check

    - name: Report nano status
      debug:
        msg: >
          Nano is {{
            'installed' if (nano_check.CommandPlugins[0].Output | trim != '') else 'not installed'
          }} on {{ inventory_hostname }}
