- name: Check if nano is installed on EKS nodes
  hosts: all
  gather_facts: false
  tasks:
    - name: Check if nano exists
      command: which nano
      register: nano_check
      ignore_errors: true

    - name: Report nano status
      debug:
        msg: >
          Nano is {{ 'installed' if nano_check.rc == 0 else 'not installed' }} on {{ inventory_hostname }}
