- name: Check if nano is installed via SSM
  hosts: all
  gather_facts: false
  connection: local  # SSM runs via API
  tasks:
    - name: Run SSM command to check for nano
      amazon.aws.aws_ssm_command:
        targets:
          - "{{ inventory_hostname }}"
        document_name: "AWS-RunShellScript"
        parameters:
          commands:
            - "which nano || echo ''"
      register: nano_check

    - name: Report nano status
      debug:
        msg: >
          Nano is {{
            'installed' if (nano_check.CommandPlugins[0].Output | default('') | trim != '') else 'not installed'
          }} on {{ inventory_hostname }}
