name: Destroy the first terraform k8s

on:
  workflow_dispatch:

jobs:
  destroy:
    name: Check installed tools
    
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Check installed tools
        run: |
          aws eks update-kubeconfig --region us-east-1 --name my-eks-cluster
          helm uninstall grafana
          kubectl delete ingress my-app -n default
          
  terraform:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        
      - name: Terraform init
        run: terraform init    
        
      - name: Terraform destroy
        run: terraform destroy -auto-approve

      - name: CD to dns module to destroy the hosted zone and certificate
        run: |
          cd dns_cert
          terraform init 
          terraform destroy -auto-approve
