name: Ingress run terraform

on:
  workflow_dispatch:


jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform init
        run: cd ingress && terraform init

      - name: Terraform plan
        run: cd ingress && terraform plan -out=tfplan

      - name: Terraform apply
        run: cd ingress && terraform apply -auto-approve tfplan


