name: Check install tool and run lb controller

on:
  workflow_dispatch:

jobs:
  setup:
    name: Check installed tools
    
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Check installed tools
        run: |
          aws eks update-kubeconfig --region us-east-1 --name my-eks-cluster
          kubectl version
          helm version
          aws --version

  install-controller:
    name: Install AWS Load Balancer Controller
    needs: setup
    runs-on: self-hosted
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::279205476473:role/github-actions-deploy-role #tells GitHub Actions to assume an IAM role in your AWS account using OIDC (OpenID Connect)
          aws-region: us-east-1

      - uses: actions/checkout@v3

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --region us-east-1 --name my-eks-cluster

      - name: Install service account
        run: kubectl apply -f serviceaacount.yaml

      - name: Install or Upgrade AWS Load Balancer Controller
        run: |
          helm repo add eks https://aws.github.io/eks-charts || true
          helm repo update

          if helm list -n kube-system | grep -q aws-load-balancer-controller; then
            echo "🔄 Helm release already exists. Running upgrade..."
            helm upgrade aws-load-balancer-controller eks/aws-load-balancer-controller \
              -n kube-system \
              --set clusterName=my-eks-cluster \
              --set serviceAccount.create=false \
              --set serviceAccount.name=aws-load-balancer-controller \
              --set region=us-east-1 \
              --set vpcId=vpc-08fe1d15298621267 \
              --set ingressClass=alb \
              --set subnets="{subnet-0b0129bd6581c9229,subnet-091c43c046e84d0a1,subnet-0225aec59124df642,subnet-0c1e534bb0f2707be}"
          else
            echo "🚀 Installing AWS Load Balancer Controller..."
            helm install aws-load-balancer-controller eks/aws-load-balancer-controller \
              -n kube-system \
              --set clusterName=my-eks-cluster \
              --set serviceAccount.create=false \
              --set serviceAccount.name=aws-load-balancer-controller \
              --set region=us-east-1 \
              --set vpcId=vpc-08fe1d15298621267 \
              --set ingressClass=alb \
              --set subnets="{subnet-0b0129bd6581c9229,subnet-091c43c046e84d0a1,subnet-0225aec59124df642,subnet-0c1e534bb0f2707be}"
          fi


  deploy-grafana:
    name: Deploy Grafana via Helm
    needs: install-controller
    runs-on: self-hosted
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::279205476473:role/github-actions-deploy-role #tells GitHub Actions to assume an IAM role in your AWS account using OIDC (OpenID Connect)
          aws-region: us-east-1
      - uses: actions/checkout@v3

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --region us-east-1 --name my-eks-cluster

      - name: Helm install Grafana
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm install grafana bitnami/grafana -f values.yaml

  apply-ingress:
    name: Apply Ingress Config
    needs: deploy-grafana
    runs-on: self-hosted
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::279205476473:role/github-actions-deploy-role #tells GitHub Actions to assume an IAM role in your AWS account using OIDC (OpenID Connect)
          aws-region: us-east-1
          
      - uses: actions/checkout@v3

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --region us-east-1 --name my-eks-cluster

      - name: Apply Ingress YAML
        run: cd ingress && kubectl apply -f ingress.yaml
