name: Check install tool and run lb controller

on:
  workflow_dispatch:

jobs:
  setup:
    name: Check installed tools
    runs-on: self-hosted
    steps:
      - name: Check installed tools
        run: |
          kubectl version
          helm version
          aws --version
  install-controller:
    name: Install AWS Load Balancer Controller
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Re-configure AWS & kubeconfig
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::279205476473:role/github-actions-deploy-role
          aws-region: us-east-1

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --region us-east-1 --name my-eks-cluster

      - name: Install service account
        run: kubectl apply -f serviceaacount.yaml

      - name: Install load balancer controller
        run: |
          helm repo add eks https://aws.github.io/eks-charts
          helm repo update
          helm install aws-load-balancer-controller eks/aws-load-balancer-controller \
            -n kube-system \
            --set clusterName=my-eks-cluster \
            --set serviceAccount.create=false \
            --set serviceAccount.name=aws-load-balancer-controller \
            --set region=us-east-1 \
            --set vpcId=vpc-00439c1ac0d5fc674 \
            --set ingressClass=alb \
            --set subnets="{subnet-01feca4e5854cd716,subnet-08146b8dd8acf5626,subnet-0b395b7f6d40d031e,subnet-08d3aa9b2f9a85d28}"

  deploy-grafana:
    name: Deploy Grafana via Helm
    needs: install-controller
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: Re-configure AWS & kubeconfig
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::279205476473:role/github-actions-deploy-role
          aws-region: us-east-1

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --region us-east-1 --name my-eks-cluster

      - name: Helm install Grafana
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm install grafana bitnami/grafana -f values.yaml

  apply-ingress:
    name: Apply Ingress Config
    needs: deploy-grafana
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: Re-configure AWS & kubeconfig
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::279205476473:role/github-actions-deploy-role
          aws-region: us-east-1

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --region us-east-1 --name my-eks-cluster

      - name: Apply Ingress YAML
        run: cd ingress && kubectl apply -f ingress.yaml
