name: Run the terraform

on:
  workflow_dispatch:


jobs:
  terraform:
    runs-on: self-hosted
    permissions:
      id-token: write  # required for OIDC
      contents: read

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
         role-to-assume: arn:aws:iam::279205476473:role/github-actions-deploy-role
         aws-region: us-east-1

      - name: Install kubectl and helm
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Run kubectl to update the kubeconfig
        run: aws eks update-kubeconfig --region us-east-1 --name my-eks-cluster
      
      - name: Intall service account to add load-balancer controller
        run: kubectl apply -f serviceaacount.yaml 
      
      - name: install load-balancer controller
        run: |
          helm repo add eks https://aws.github.io/eks-charts
          helm repo update
          helm install aws-load-balancer-controller eks/aws-load-balancer-controller \
            -n kube-system \
            --set clusterName=my-eks-cluster \
            --set serviceAccount.create=false \
            --set serviceAccount.name=aws-load-balancer-controller \
            --set region=us-east-1 \
            --set vpcId=vpc-00439c1ac0d5fc674 \
            --set ingressClass=alb \
            --set subnets="{subnet-01feca4e5854cd716,subnet-08146b8dd8acf5626,subnet-0b395b7f6d40d031e,subnet-08d3aa9b2f9a85d28}"

      - name: helm install repo 
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm install grafana bitnami/grafana -f values.yaml

      - name: Run ingress yaml
        run: cd ingress && kubectl apply -f ingress.yaml

